### ISSUE TITLE
[crates] Add versions information to raw items

### ISSUE THREAD

**Issue by acs** [grimoirelab/perceval-mozilla#11]
The raw item delivered by the perceval crates backend does not include the versions information for a crate. This information includes the mapping between the version id and the version string, and also, the downloads per version of a crate.

This information can be extracted for all crates from https://crates.io/api/v1/crates/rand/versions and it is directly included in https://crates.io/api/v1/crates/rand.

In the crate dict in https://crates.io/api/v1/crates/rand there is a version list, but it just includes the version ids available for the crate, not the full information included in the versions dict.

**Comment by sduenas** [comment]
@valeriocos can you check this, please?

**Comment by sduenas** [comment]
Fixed by #12
